import Head from "next/head"
import Link from "next/link"
import { Navbar } from "../Navbar"

import styles from "./MainLayout.module.css"
import { FC, PropsWithChildren } from 'react';

export const MainLayout: FC<PropsWithChildren> = ({children}) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Cositas nuevas con Next.JS</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <Navbar></Navbar>
          {/* <Head>
            <title>Cositas nuevas con Next.JS2</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head> */}
    
          <main className={styles.main}>
            
            {children}
    
          </main>
        </div>
      )
}
